name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - name: Setup Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@release/v1

    - uses: actions/checkout@v4

    - name: Enable Windows 64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: sed -e "50,54s/^#//" Makefile > Makefile.nmake

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: set OSPLAT=x64 & nmake -f Makefile.nmake

    - name: Run
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: bin.ntx64\jam.exe -v

    - name: Package
      shell: bash
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          tag=${{ github.ref }}
          release_name="jam-$tag-${{ matrix.target }}"

          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip "${release_name}.zip" "./bin.ntx64/*"
          else
            tar czvf "${release_name}.tar.gz" "bin.ntx64/"
          fi

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "jam-*"
